<form id="editor">
	<!-- <pre id="editable" contenteditable="true">
		<div>Paste your tasks here</div>
	</pre> -->
	<textarea id="textarea" style="width: 96%; height: 400px; font-size: 10px;">
/middagsselskap 	
	@office @telenor 
	- paprika osv @grimstadgata
	- melk

	@calls tomorrow
	- jan @home //explain something tomorrow
	- espen 
	- hans 
	
	@www 
	- http://www.cmdtask.com today

	</textarea>
	
</form>