<span class="logo">+task:</span>
<div class="syntax">	
	<span id="section">{$section}</span>	
	<!-- <span class="task-text">[i18n(TASK_TEXT)]</span>
	<span class="key contexts">@[i18n(CONTEXT)]</span>
	<span class="key projects">?[i18n(PROJECT)]</span>
	<span class="key tags">#[i18n(TAG)]</span>
	<span class="key date">[i18n(TIME)]</span>
	<span class="desc">/*[i18n(COMMENTS_EXPLAIN)]*/</span> -->
</div>
